Stanford-Online/configuration

playbooks/edx-west/prod-jumpbox.yml, playbooks/edx-west/stage-jumpbox.yml
@jbau This reminds me of something we should talk about..
=> Add Azim to jumpbox

playbooks/roles/user/defaults/main.yml, playbooks/roles/user/tasks/main.yml
@stvstnfrd 
ansible code to remove old users
=> allow removal of old users

playbooks/edx-west/prod-xqueue.yml
=> Change prod_xqueue.yml to point to util machines

playbooks/roles/security/files/tmp/GHOST.c, playbooks/roles/security/tasks/security-ubuntu.yml
apply glibc update if vulnerable to CVE-2015-0235
Conflicts:
playbooks/roles/security/tasks/security-ubuntu.yml
=> Patch GHOST vulnerability

playbooks/edx-west/data-suclass-insights.yml
=> Configure insights for suclass

playbooks/edx-west/prod-maint.yml
=> Add playbook for maint page

playbooks/roles/edxapp/tasks/deploy.yml, playbooks/roles/nginx/defaults/main.yml, playbooks/roles/nginx/tasks/main.yml, playbooks/roles/notifier/defaults/main.yml
This PR resolves configuration issues found after the recent merge from upstream.
=> Fix post-merge issues

playbooks/edx-west/prod-shib.yml
=> Add prod-shib playbook, WIP for lagunita

playbooks/edx-west/suclass-prod-app.yml
=> Add lms-preview to nginx for suclass

playbooks/roles/certs/defaults/main.yml
=> Switch to using Open edX certs repo

playbooks/edx-west/.gitignore, playbooks/edx-west/carnegie-prod-app.yml, playbooks/edx-west/carnegie-prod-forum.yml, playbooks/edx-west/carnegie-prod-phpmyadmin.yml, playbooks/edx-west/carnegie-prod-worker.yml, playbooks/edx-west/cme-prod-app.yml, playbooks/edx-west/cme-prod-forum.yml, playbooks/edx-west/cme-prod-worker.yml, playbooks/edx-west/prod-app.yml, playbooks/edx-west/prod-forum.yml, playbooks/edx-west/prod-maint.yml, playbooks/edx-west/prod-postgres-test-edxapp.yml, playbooks/edx-west/prod-shib.yml, playbooks/edx-west/prod-worker.yml, playbooks/edx-west/prod-xqueue.yml, playbooks/edx-west/stage-all.yml, playbooks/edx-west/stage-app.yml, playbooks/edx-west/stage-debug.yml, playbooks/edx-west/stage-forum.yml, playbooks/edx-west/stage-rabbit.yml, playbooks/edx-west/stage-worker.yml, playbooks/edx-west/stage-xqueue.yml, playbooks/edx-west/suclass-prod-app.yml, playbooks/edx-west/suclass-prod-forum.yml, playbooks/edx-west/suclass-prod-worker.yml, playbooks/edx-west/users.yml
@stvstnfrd 
https://lagunita.atlassian.net/browse/LE-648
=> Update deprecated references to edx-secret

playbooks/roles/edxapp/defaults/main.yml, playbooks/roles/edxapp/templates/workers.conf.j2
=> Add codejail proxy environment variable for worker

playbooks/roles/nginx/tasks/main.yml, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/maintenance.j2, playbooks/roles/nginx/templates/edx/var/nginx/server-static/maintenance.html.j2
S3 maintenance page looks like it integrates with LMS/CMS and is not standalone, so I think we want to do this for now.
=> Add Stanford maintenance page

playbooks/roles/common/defaults/main.yml, stanford/edxapp.yml
@stvstnfrd Stanford-Online/configuration-secure#188
=> Include var_file for common env variables

playbooks/roles/forum/defaults/main.yml, playbooks/roles/notifier/templates/notifier-celery-workers-supervisor.sh.j2, playbooks/roles/notifier/templates/notifier-scheduler-supervisor.sh.j2
=> Use forked forum repo and fix notifier supervisor templates

stanford/forum.yml
=> Parameterize forum machine

playbooks/roles/certs/defaults/main.yml
=> Change default install branch for cert tpls RC

playbooks/roles/browsers/tasks/main.yml
=> Once this mv runs on the base box, it fails on provision

playbooks/roles/edxapp/defaults/main.yml
@stvstnfrd & @kluo - config changes to coincide with platform one
=> Remove ACCOUNT_NAME setting and default

playbooks/roles/edxapp/defaults/main.yml
@stvstnfrd @caesar2164 Checkout registration footer disclaimer change edxapp config
=> Add default edxapp registration disclaimer

bin/print-ssh-config
Pros:
- you get an entry for everything
- no need to mess with DNS
Cons:
- ip addresses can go stale; fixed by rerunning script
=> Create script to generate ~/.ssh/config file

playbooks/group_vars/all, stanford/certificates.yml, stanford/db-grader-proxy.yml, stanford/debug.yml, stanford/edxapp.yml, stanford/elasticsearch.yml, stanford/forum.yml, stanford/insights-api.yml, stanford/insights.yml, stanford/jumpbox.yml, stanford/maintenance.yml, stanford/notifier.yml, stanford/rabbit.yml, stanford/shib.yml, stanford/users.yml, stanford/worker.yml, stanford/xqueue.yml
We should better leverage the `group_vars` diretories.
=> Set secure_dir once for everywhere

playbooks/roles/edxapp/defaults/main.yml
=> Add tracking backends config to json

playbooks/roles/edxapp/defaults/main.yml
This reverts commit f7939b01de6c7bee30793f1b50aa736aeb0060de.
This goes with https://github.com/Stanford-Online/edx-platform/pull/494/commits/04ed6d54c969602f2c497346aace2ef3ddad8718
@stvstnfrd
=> Revert "Add default edxapp registration disclaimer"

playbooks/roles/edxapp/defaults/main.yml
=> Release Arabic

playbooks/roles/filebeat/defaults/main.yml, playbooks/roles/filebeat/handlers/main.yml, playbooks/roles/filebeat/tasks/main.yml, playbooks/roles/filebeat/templates/filebeat.yml.j2, playbooks/roles/kibana/defaults/main.yml, playbooks/roles/logstash/defaults/main.yml, playbooks/roles/logstash/tasks/main.yml, playbooks/roles/logstash/templates/logstash.conf.j2, playbooks/roles/logstash/templates/logstash.init.j2, playbooks/roles/topbeat/defaults/main.yml, playbooks/roles/topbeat/handlers/main.yml, playbooks/roles/topbeat/tasks/main.yml, playbooks/roles/topbeat/templates/topbeat.yml.j2, stanford/logs-backend.yml, stanford/logs-frontend.yml, stanford/logs-sender.yml
@stvstnfrd 
first draft- I am going to pull out the funny unnecessary changes but haven't done that yet
=> Deploy log analytics infrastructure- ELK stack

playbooks/roles/filebeat/defaults/main.yml, playbooks/roles/filebeat/tasks/main.yml, playbooks/roles/filebeat/templates/filebeat.yml.j2, playbooks/roles/logstash/templates/logstash.conf.j2, playbooks/roles/topbeat/defaults/main.yml, stanford/logs-sender.yml
=> ELK stack grok fixes

playbooks/roles/filebeat/defaults/main.yml, playbooks/roles/filebeat/templates/filebeat.yml.j2, playbooks/roles/logstash/templates/logstash.conf.j2, playbooks/roles/topbeat/defaults/main.yml, stanford/logs-sender.yml
=> regex take two

playbooks/roles/edxapp/defaults/main.yml
=> Reduce cms worker count to 1 per core

playbooks/roles/elasticsearch/templates/edx/etc/elasticsearch/elasticsearch.yml.j2, stanford/beats.yml, stanford/elasticsearch.yml, stanford/jumpbox.yml, stanford/kibana.yml, stanford/logstash.yml, stanford/playbooks/provision.yml, stanford/playbooks/rotate.yml, stanford/stage/beats.yml, stanford/stage/elasticsearch-elk.yml, stanford/stage/group_vars/all, stanford/stage/kibana.yml, stanford/stage/logstash.yml
=> Provision Stage ELK stack

playbooks/roles/filebeat/templates/filebeat.yml.j2
=> Fix regex syntax error

playbooks/roles/logstash/templates/logstash.conf.j2, playbooks/roles/nginx/templates/edx/app/nginx/sites-available/kibana.j2
=> Direct heartbeats into their own log to avoid pollution

playbooks/roles/logstash/files/Dashboard-1.json
@stvstnfrd here is the dashboard, no need to merge yet
=> Configured dashboard

playbooks/roles/nginx/templates/edx/app/nginx/sites-available/kibana.j2
=> Unfork kibana basic_auth

playbooks/roles/certs/tasks/deploy.yml
=> Settings changes required for cert deploys

playbooks/vagrant-devstack.yml
At least on devstack, I don't know why we wouldn't want master here.
=> Install configuration/master in devstack

vagrant/release/devstack/Vagrantfile
=> Add nfs directory to facilitate xblock developement.

vagrant/release/devstack/Vagrantfile
=> Add nfs directory for generated reports.

playbooks/roles/edxapp/defaults/main.yml
=> Install StatTutor XBlock

playbooks/roles/edxapp/defaults/main.yml
@caesar2164 @stvstnfrd @caseylitton
=> Release Vietnamese

stanford/roles/cluster/defaults/main.yml, stanford/roles/cluster/tasks/main.yml
but keep it private by default.
=> Allow new instances to have a public IP address

playbooks/roles/edxapp/defaults/main.yml
=> Add Privacy Policy link and checkbox

playbooks/roles/nginx/templates/edx/app/nginx/sites-available/static-files.j2
@stvstnfrd & @dcadams 
Configuration Pull Request
---
Make sure that the following steps are done before merging
=> Whitelist JSON files for stattutor xblock

stanford/lagunita/group_vars/all, stanford/stage/group_vars/all, stanford/suclass/group_vars/all
@stvstnfrd 
Configuration Pull Request
---
Make sure that the following steps are done before merging
=> Update notifier logo image URLS

stanford/suclass/group_vars/all
Configuration Pull Request
---
Make sure that the following steps are done before merging
=> WIP: Remove PP & ToS on suclass registration form

playbooks/roles/edxapp/defaults/main.yml
=> Adds value for twitter account setting

stanford/suclass/group_vars/all
=> Skip course listing on Suclass, which redirects home to dashboard

stanford/suclass/group_vars/all
This reverts commit 39efbb87d060619a09e7636d589802489ab2f529.
@stvstnfrd @caesar2164
=> Revert "Skip course listing on Suclass, which redirects home to dashboard

stanford/roles/cluster/defaults/main.yml, stanford/roles/cluster/tasks/instance.yml, stanford/roles/cluster/tasks/main.yml
Prerequisite PR for insights deploy pr.
How would one go about testing this.
=> Split out instance creation from the cluster.

stanford/roles/deployment/defaults/main.yml, stanford/roles/deployment/tasks/main.yml
This shouldn't have been split out in the first place.
=> Consolidate variables for public subnet name

stanford/playbooks/scheduler.yml, stanford/roles/cluster/defaults/main.yml, stanford/stage/scheduler.yml
=> Rename analytics-jenkins play to scheduler.

stanford/cme/es.yml, stanford/lagunita/es.yml, stanford/stage/es.yml, stanford/suclass/es.yml
@stvstnfrd  I believe I need these files in order to run this play.
=> Add missing yml files to ElasticSearch cluster so it can be run.

playbooks/roles/edxapp/defaults/main.yml
=> Release Chinese and standardize language strings

playbooks/roles/edxapp/defaults/main.yml
=> Release Russian

playbooks/roles/edxapp/defaults/main.yml
=> Release Mongolian translations

stanford/lagunita/scheduler.yml
=> File to create lagunita scheduler.

stanford/playbooks/es.yml, stanford/roles/cluster/defaults/main.yml, stanford/stage/es.yml
=> Remove the es play since it didn't work out.

stanford/lagunita/scheduler.yml
Changed from default of t2.micro to t2.medium.
=> Change size of lagunita scheduler box.

stanford/lagunita/analytics-api1.yml, stanford/lagunita/analytics-api2.yml
=> Lagunita analytics-api play.

stanford/suclass/scheduler.yml
=> Suclass scheduler.

stanford/cme/group_vars/all
=> Add CME footer text settings

playbooks/roles/edxapp/defaults/main.yml
=> Hide country field from registration

stanford/bin/audit-iam-users
```sh
mkvirtualenv configuration
workon configuration
pip install boto3
./stanford/bin/audit-iam-users
```
=> Create script to audit AWS user accounts

stanford/cme/users.yml, stanford/playbooks/users.yml
where we're still using the old, dynamic inventory.
=> Fix user play on CME branch

stanford/bin/elb-add, stanford/bin/elb-remove, stanford/bin/manage.sh
Not that these are use much, if ever, anymore,
but I'd like to consolidate our scripts.
=> Migrate helper scripts

playbooks/roles/edxapp/defaults/main.yml
to fix issues with the test suite and sandbox/devstack deploys.
=> Provide FORUM_MONGO defaults for edxapp

playbooks/roles/edxapp/templates/workers.conf.j2, stanford/lagunita/worker3.yml, stanford/stage/worker3.yml
For persistent grades backfill task.
=> Create grades_backfill queue

AUTHORS, playbooks/vagrant-buildbot.yml, stanford/roles/buildbot_common/defaults/main.yml, stanford/roles/buildbot_master/defaults/main.yml, stanford/roles/buildbot_master/meta/main.yml, stanford/roles/buildbot_master/tasks/main.yml, stanford/roles/buildbot_master/templates/master.cfg.j2, stanford/roles/buildbot_master/templates/openedx_buildbot/configuration.py.j2, stanford/roles/buildbot_master/templates/openedx_buildbot/edxapp.py.j2, stanford/roles/buildbot_worker/defaults/main.yml, stanford/roles/buildbot_worker/meta/main.yml, stanford/roles/buildbot_worker/tasks/main.yml, vagrant/base/buildbot/README.md, vagrant/base/buildbot/Vagrantfile
This isn't used live, not is it confirmed to be working in its current
state, but I'd like to merge it now, for posterity's sake.
We may end up deleting the code later (or hopefully fixing it up!),
but I'd like to close this PR that's been sitting around.
The code is isolated to its own custom role(s), so it shouldn't affect
anything else.
- [1] https://github.com/Stanford-Online/configuration/pull/166
Rebased-by: stv <stv@stanford.edu>
=> Set up buildbot roles and vagrant box

stanford/bin/send-email.py
This way we don't need to add them manually!
=> Use the existing version of params from secrets
