playbooks/roles/edxapp/defaults/main.yml

Default setting of DISPLAY_COURSE_TILES
This was introduced to allow no tiles to be displayed on the SuClass home page.

Set default of false for DISPLAY_COURSE_TILES

---

playbooks/roles/edxapp/defaults/main.yml

This was causing issues where staticfiles caches to one machine would
affect others; i.e., deploying to privateprod would affect prod.

Segregate machine-specific cache keys

---

jenkins/cut-release
jenkins/send-email.py

This is intended to be run as a Jenkins Job.
It should be configured with the parameters:
- `BRANCH_OLD = origin/rc`
- `BRANCH_NEW = origin/master`
This command lists the commits
that _do_ exist in `${BRANCH_NEW}`,
but _don't_ exist in `${BRANCH_OLD}`.
So:
- `BRANCH_OLD=origin/rc BRANCH_NEW=origin/master`
tells us what would be in the release candidate _if_ we cut it right now.
while:
- `BRANCH_OLD=origin/release BRANCH_NEW=origin/rc`
tells us what _is_ on RC but not yet released to production.

Add helper script to compile release notes across repos

---

playbooks/roles/edxapp/defaults/main.yml

We have been experiencing issues in production with memory (over-)utilization.
While we are restarting the gunicorn workers every `n` requests (see:
`EDXAPP_MAX_REQUESTS`), this seems insufficent.
TODO: write more here before merging.

Reduce gunicorn worker count for LMS/CMS

---

playbooks/ec2.ini

We need this since multiple users may run this from the same machine,
*cough* _jenkins_ *cough*
We had been overriding this separately in the various ec2.ini's, but
this moves us closer to sharing configuration files.

Update default cache path to local/hidden

---

playbooks/roles/edxapp/defaults/main.yml

@stvstnfrd @ggg PR that adds LICENSING feature flag to cms and lms configuration.  Defaults to seeing the footer lms if it exists but not allowing additional footers to be set cms.

Add licensing footer feature flag to lms and cms

---

playbooks/roles/logstash/templates/logstash.conf.j2
playbooks/roles/nginx/defaults/main.yml
playbooks/roles/nginx/templates/edx/app/nginx/sites-available/kibana.j2
stanford/logs-frontend.yml

- Make the host nginx believes elasticsearch lives on to be configurable
- Change a variable name to the clearer version in logstash config
- Make sure frontend nginx adds kibana as an enabled site

Fix minor configuration errors in ELK stack

---

playbooks/edx_sandbox.yml

The notifier role was first added to this play in in December 2014 [1].
This PR was primarily notifier-related.
See: [3]
This role was again added, this time without a configured interval, in
February of 2015 [2]. This role was added alongside several others.
Perhaps the duplication was overlooked at the time?
See: [4]
[1] https://github.com/edx/configuration/commit/83053b52863e230d38ee0c2c2b2a71601725fe90
[2] https://github.com/edx/configuration/commit/cef9193ddf7b5c450be44d55e4ffd620a9e73392
[3] https://github.com/edx/configuration/blob/141ef9d2fd3c4788b04309e55c15f9de03adb030/playbooks/edx_sandbox.yml#L59
[4] https://github.com/edx/configuration/blob/141ef9d2fd3c4788b04309e55c15f9de03adb030/playbooks/edx_sandbox.yml#L49

Stop deploying notifier twice on sandboxes

---

playbooks/roles/certs/defaults/main.yml

@caesar2164 There was no default specified here in `configuration`, so this failed on sandboxes/devstacks. For whatever reason, we were setting this in secrets..

Define missing certs variable

---

playbooks/roles/certs/defaults/main.yml
playbooks/roles/certs/tasks/main.yml
playbooks/roles/certs/templates/gpg-trust.j2

instead of manually writing a variable out to file.
The newline was no longer rendering properly. This may be related to a
previous Ansible upgrade; maybe it's been broken longer.
I only noticed when creating new devstacks/sandboxes; this task isn't
run on machines where the file already existed.

Write GPG-trust with template

---

playbooks/roles/certs/defaults/main.yml
playbooks/roles/certs/tasks/deploy.yml

We don't always have this set for sandboxes/devstacks.

Install cert templates only when defined

---

playbooks/roles/elasticsearch/defaults/main.yml
playbooks/roles/elasticsearch/templates/edx/etc/elasticsearch/elasticsearch.yml.j2
stanford/elasticsearch.yml

Let's hide this abstraction from the public/shared roles, and instead
isolate the Cluster/Deployment logic within our own plays.
This replaces https://github.com/Stanford-Online/configuration/pull/137

Remove Cluster/Deployment dependency from roles

---

playbooks/roles/analytics_api/defaults/main.yml

There are some cases, like sandboxes and devstacks, where this isn't set
properly. We can't set COMMON_GIT_PATH universally because there are
some repositories that we still need from edx.

Install Stanford's Analytics API explicitly

---

playbooks/roles/edxapp/tasks/service_variant_config.yml

Otherwise, SECRET_KEY is undefined and things fall apart (required in dj18).
This was extracted from an upstream commit [1][2].
[1] 924a7a01ba2ad4322b4ca5dd08431d3fff00f4f2
[2] https://github.com/edx/configuration/commit/924a7a01ba2ad4322b4ca5dd08431d3fff00f4f2#diff-295d2728f4e59240e89172aca35bfd3c

Use aws config when running migrations

---

playbooks/roles/edxapp/defaults/main.yml

The Queries tab in the instructor dashboard allows them to query by section and problem type. This commit adds
to the types of problems (by block_type) that can be queried.

Add queryable problem types to instructor dashboard

---

stanford/playbooks/cluster.yml

since Ubuntu 16.04 (xenial) only comes with Python3, by default.

Bootstrap new instances with Python2

---

stanford/roles/cluster/tasks/main.yml

This is now supported with Ansible 2.1+;
we're running 2.2.

Tag load balancers on creation

---

stanford/roles/cluster/tasks/main.yml

The former syntax did not work on OSX.

Use cross-platform `date` syntax

---

stanford/cme/group_vars/all
stanford/lagunita/group_vars/all
stanford/sandbox/group_vars/all
stanford/stage/group_vars/all
stanford/suclass/group_vars/all

While this was already set in the role's `defaults/main.yml`,
we need this here so reference it easily w/in other roles.

Set default CLUSTER_NUMBER

---

playbooks/roles/edxapp/defaults/main.yml

We're no longer using the `env` variable, instead opting for the
standardized `COMMON_DEPLOYMENT` instead.

Fix memcache keys

---

playbooks/roles/nginx/templates/edx/app/nginx/sites-available/shib-only.j2

@caesar2164 @stvstnfrd 
This fix doesn't address the fact that intrepid users can go to /register and make a suclass account without going through TPA

Remove /register redirect which causes TPA to endlessly loop

---

playbooks/roles/edxapp/defaults/main.yml
stanford/stage/group_vars/cme

After transitioning to the ThirdPartyAuth djangoapp,
we're no longer using the old-style shibboleth login.
We longer need the main feature flag; it defaults to `False`.
The `_CMS` suffixed variable was custom at Stanford (I think),
so we can nuke it too.

Remove deprecated AUTH_USE_SHIB flag

---

stanford/roles/cluster/defaults/main.yml

This was erroneously configured to open RabbitMQ ports;
this was a mistake.

Fix forum ELB

---

stanford/roles/cluster/tasks/main.yml
stanford/roles/deployment/tasks/main.yml

when updating the route tables.
References:
- [1] http://docs.ansible.com/ansible/latest/ec2_vpc_route_table_module.html

Stop purging unspecified routes

---

playbooks/roles/nginx/templates/edx/app/nginx/sites-available/shib-only.j2

Redirect is now handled in Django via FORCED_TPA_PROVIDER_ID setting
@stvstnfrd @caesar2164

Remove lms nginx redirects for suclass TPA

---

stanford/stage/worker1.yml

@kluo Looks like we only made this change to cleanup `edxapp`, but missed it on the worker.

Install rc branch to stage worker boxes

---

playbooks/roles/jenkins_master/defaults/main.yml

It looks like this version disappeared from the downloads page within
the past few weeks. I successfully ran this play less than a month ago,
but it started failing a week or two ago, due to the 404 upon download.
I'm admittedly a bit confused as to why there appears to be at least 3
different minor versions of jenkins in use [1][2][3] (plus a major bump
on the build server?! [4]), so I simply cribbed the version used by the
`tools_jenkins` role.
References:
- [1] jenkins_version: "1.638"
- [2] jenkins_tools_version: "1.651.3"
- [3] jenkins_admin_version: "1.658"
- [4] build_jenkins_version: jenkins_2.60.3

Bump installed jenkins_master version

---

playbooks/roles/jenkins_master/defaults/main.yml

since it now longer exists.
There is an upstream PR for this change, but it includes unrelated
changes that we don't want/need now.

Remove custom jenkins plugin

---

stanford/roles/cluster/tasks/main.yml

In what was presumably a copy/paste relic, the `cluster` role mistakenly
used the `deployment` role's variable name prefix, overwriting the
latter's variable.
This hadn't caused any issues to date, though it possibly could down the
line; each role should only update its own variables.

Rename cluster role variable

---

stanford/roles/cluster/tasks/instance.yml

The original default was standard/magnetic.

Attach general purpose SSD volumes to EC2, by default

---

stanford/roles/cluster/tasks/main.yml
stanford/roles/deployment/defaults/main.yml
stanford/roles/deployment/tasks/main.yml

We were doing this already for the VPC (via `VPC_ID`), as well as the
NAT gateway (via  the `if_exist_do_not_create` flag), but this now
extends the behavior to all of the other resources too.
This now covers:
- internet gateway
- public subnet
- public route table
There's no need to touch these any more often than necessary and I still
worry about accidentally breaking (or even inadvertently modifying)
existing resources when provisioning new clusters.

Make deployment resource creation optional

---

stanford/roles/cluster/tasks/main.yml
stanford/roles/deployment/tasks/main.yml

Now each task universally exports the ID of the resource it creates.

Set more deployment facts

---

playbooks/roles/nginx/templates/edx/app/nginx/sites-available/cms.j2
playbooks/roles/nginx/templates/edx/app/nginx/sites-available/lms.j2
playbooks/roles/nginx/templates/edx/app/nginx/sites-available/loggable.j2

This has long been a frustration of mine.
It's a pain to be `tail`ing logs and have the screen fill up with
heartbeat checks every few seconds.
I was prompted to revisit this following the recent issue with log files
taking up a significant amount of disk space.
Note: only successful attempts are excluded from the logs.
Should an error occur, it will still be logged to the error log file.

Omit successfull `/heartbeat` requests from logs

---

stanford/stage/group_vars/all

Since stage is just used for testing, we're not concerned with HA
(High Availability). By explicitly pinning the `deployment_subnet_index`
to zero, we can ensure that only a single subnet will be created per
cluster.

Force stage to be a single-AZ deployment

---

stanford/playbooks/beats.yml
stanford/playbooks/db-grader-proxy.yml
stanford/playbooks/elasticsearch_elk.yml
stanford/playbooks/insights-api.yml
stanford/playbooks/insights.yml
stanford/playbooks/kibana.yml
stanford/playbooks/logstash.yml
stanford/playbooks/maintenance.yml

It has been deprecated and subsequently removed from future ansible
releases, in favor of the `become` keyword.

Replace sudo inside playbooks

---

stanford/playbooks/cluster.yml

It looks like this hasn't actually been working,
because the `tasks` section isn't executed prior to the `roles`.
By just splitting this out into two separate plays,
we can ensure they are executed in the proper order.
And since the former play is simply an include,
it doesn't rely on any side-effects of the latter.

Fix cluster role's optional include

---

stanford/playbooks/insights.yml
stanford/stage/insights1.yml

Required for Insights play to run.
t2.micro doesn't have enough memory for the install.

Fix insights play

---

stanford/AUTHORS
vagrant/release/devstack/Vagrantfile

The devstack still included a reference to an expired edx key.
Until it was removed, any attempts to run `apt-get update` would fail.
This prevented us from creating a new devstack.

Fix expired key in devstack

---

playbooks/roles/ecommerce/defaults/main.yml

The ecommerce playbook installs edx master but that version does not have the requirements/optional.txt file.

Remove reference to ecommerce requirements file that no longer exists.

---

stanford/roles/cluster/defaults/main.yml

for using the AWS Elasticsearch Service.
Using HTTP also allows us to use internal DNS names w/out worrying about
SSL cert issues on the default AWS hostname.

Open HTTP/S ports for elasticsearch

---

stanford/stage/inventory.yaml

Remove `new.` prefix from stage hosts

---

playbooks/roles/edxapp/defaults/main.yml

else creation of the JSON fails for non-SUclass deployments.

Add default for MAX_ENROLLEES_FOR_METRICS_USING_DB

---

playbooks/vagrant-devstack.yml
vagrant/release/devstack/Vagrantfile

since a recent elasticsearch causes provisioning to fail [1].
The vagrant-based devstack is deprecated and will not be used following
our upgrade to hawthorn.
- [1] Package elasticsearch has conffile prompt and needs to be upgraded
manually

Disable SECURITY_UPGRADE_ON_ANSIBLE in devstack

---

stanford/bin/cut-release-branch

This extends https://github.com/Stanford-Online/configuration/pull/301 by:
- rebasing on master
- cleaning up the sender/email/datestamp
Unless you feel strongly about the convention in your implementation, @dcadams ,
I'd really like to use these (in my additional commit) as they restore the conventions we used previously;
it makes searching email (and reading the subjects) easier.

Update email sending for cut-release-branch

---

playbooks/roles/edxapp/defaults/main.yml

since we've opted to run fewer, larger instances.
Hopefully, this will allow for more utlization of our resources and
prevent cases where the queue becomes too backed up.

Increase grade report concurrency on worker boxes

---

stanford/bin/dump-logs

This can be used to crawl and dump all logs (edx and system) and archive them into a single tarball.
This will initially be used for CME, then elsewhere.

Dump deployment logs
